### ISSUE TITLE
Información real

### ISSUE THREAD

**Issue by FranciscoSegura07** [ISWPOLI/PoliLockers#69]
Recolectar información real referente a los lockers de la IUPG

**Comment by FranciscoSegura07** [comment]
Tiempo estimado para esta tarea: 4 horas

**Comment by miguelp123** [comment]
El día 23 de mayo se solicita información en el bloque A, pero la persona encargada no se encuentra en el momento, nos facilitan un correo para contactar al encargado.

**Comment by miguelp123** [comment]
Se envía correo al encargado William R. Angel, esperando respuesta.

**Comment by miguelp123** [comment]
La tarea se mueve del sprint AVANCE al sprint ENTREGA FINAL, dado que no se ha obtenido respuesta sobre la informacion de los lockers por parte de la oficina de activos

**Comment by miguelp123** [comment]
Se obtiene respuesta de William Angel, pero nos indica que no tiene esa informacion, que debemos pedir autorización en otra dependencia.

**Comment by miguelp123** [comment]
EL dia Miercoles 31 de mayo, se solicita nuevamente informacion en el bloque A, donde nos dirigen con Gustavo Espinel, quien emite autorizacion a seguridad para realizar el conteo personalmente.
